version: '3.8'

services:
  test-neo4j:
    image: neo4j:4.2
    ports:
      - published: $TEST_NEO4J_HTTP_PORT
        target: 7474
      - published: $TEST_NEO4J_BOLT_PORT
        target: 7687
    environment:
      NEO4J_AUTH: none
      NEO4JLABS_PLUGINS: '["apoc"]'

  test-mysql:
    image: mysql:8
    ports:
      - published: $TEST_MYSQL_PORT
        target: 3306
    environment:
      MYSQL_ROOT_PASSWORD: $TEST_MYSQL_PASSWORD
      MYSQL_DATABASE: $TEST_MYSQL_DATABASE
