version: '3.8'

services:
  neo4j:
    image: neo4j:4.2
    ports:
      - published: $NEO4J_HTTP_PORT
        target: 7474
      - published: $NEO4J_BOLT_PORT
        target: 7687
    healthcheck:
      test: wget http://localhost:7474/browser -O-
      interval: 5s
      timeout: 3s
      retries: 30
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      NEO4JLABS_PLUGINS: '["apoc"]'
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-import:/var/lib/neo4j/import
      - neo4j-plugins:/plugins

  mysql:
    image: mysql:8
    ports:
      - published: $MYSQL_PORT
        target: 3306
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 1s
      timeout: 3s
      retries: 30
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes:
      - mysql-data:/var/lib/mysql

  imgproxy:
    image: darthsim/imgproxy:latest
    ports:
      - published: $IMGPROXY_PORT
        target: 8080
    environment:
      IMGPROXY_KEY: $IMGPROXY_KEY
      IMGPROXY_SALT: $IMGPROXY_SALT

volumes:
  neo4j-data:
  neo4j-logs:
  neo4j-import:
  neo4j-plugins:
  mysql-data:
  imageproxy-redis-data:
