FROM node:14.16.1-slim

WORKDIR /app

COPY prisma/package.json prisma/yarn.lock prisma/schema.prisma ./
COPY prisma/migrations ./migrations

RUN yarn install --frozen-lockfile && yarn cache clean

CMD ["yarn", "prisma", "migrate", "deploy"]
