proto_outdir = "./proto"

[[dependencies]]
  target = "github.com/henken-club/bookcover-grpc-service/proto"
  branch = "main"

[[dependencies]]
  target = "github.com/henken-club/account-grpc-service/proto"
  branch = "main"
