name: Build

on:
  push:
    branches:
      - main
  pull_request:

env:
  APP_IMAGE_NAME: prototype-backend
  PRISMA_MIGRATE_IMAGE_NAME: prototype-backend-prisma-migrate

jobs:
  ts-check:
    name: TS Compiler
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run ts-check

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn prisma generate
      - run: yarn run build

  docker-app:
    name: Docker for app
    needs:
      - ts-check
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile
      - uses: docker/setup-buildx-action@v1
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/henken-club/${{ env.APP_IMAGE_NAME }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'push' }}
          context: .
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  docker-prisma-migrate:
    name: Docker for prisma-migrate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: prisma/Dockerfile
      - uses: docker/setup-buildx-action@v1
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/henken-club/${{ env.PRISMA_MIGRATE_IMAGE_NAME }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'push' }}
          context: prisma
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
