name: DevOps

on:
  push:
    branches:
      - main
  pull_request:

env:
  BACKEND_IMAGE_NAME: prototype-backend
  PRISMA_MIGRATE_IMAGE_NAME: prototype-backend-prisma-migrate

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.4.2
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run lint:eslint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.4.2
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run lint:prettier

  cspell:
    name: cspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.4.2
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run lint:cspell

  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.4.2
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run typecheck

  test-unit:
    name: Unit Test
    runs-on: ubuntu-latest

    env:
      TEST_NEO4J_URL: bolt://localhost:7687
      TEST_PRISMA_DATABASE_URL: mysql://root:@localhost:3306/testdb

    services:
      neo4j:
        image: neo4j:4.2
        env:
          NEO4J_AUTH: none
          NEO4JLABS_PLUGINS: '["apoc"]'
        ports:
          - 7474:7474
          - 7687:7687
        options: >-
          --health-cmd "wget http://localhost:7474/browser -O-"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5
      mysql:
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.4.2
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn run test:unit

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.4.2
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: yarn prisma generate
      - run: yarn run build

  docker-backend:
    name: Docker for backend
    needs:
      - typecheck
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile
      - uses: docker/setup-buildx-action@v1
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/henken-club/${{ env.BACKEND_IMAGE_NAME }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'push' }}
          context: .
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  docker-prisma-migrate:
    name: Docker for prisma-migrate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile.prisma-migrate
      - uses: docker/setup-buildx-action@v1
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/henken-club/${{ env.PRISMA_MIGRATE_IMAGE_NAME }}
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'push' }}
          context: .
          file: Dockerfile.prisma-migrate
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
